name: lightgbm-env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
    - lightgbm
    - scikit-learn
    - pandas
    - numpy
    - mlflow
    - azureml-mlflow
    - azureml-inference-server-http
    - joblib